<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=400 height=100></p>

Этот ноутбук посвящён основам  библиотеки PyTorch.

## Введение

На текущее время было реализовано несколько различный фреймворков глубокого обучения. Разница между ними заключается во внутренних принципах вычислений. Например, в **[Caffe](http://caffe.berkeleyvision.org/)** и **[Caffe2](https://caffe2.ai/)** вы пишете код, используя некоторые «готовые блоки» (как и LEGO). На данный момент это уже история, сейчас **Caffe** стал частью **PyTorch**. 
В **[TensorFlow](https://www.tensorflow.org/)** вы сначала объявляете граф вычислений, затем компилируйте его и используйте для вывода / обучения (`tf.session ()`). Кстати, теперь в TensorFlow (начиная с версии 1.10) есть функция [Eager Execution](https://www.tensorflow.org/guide/eager), которая может быть полезна для быстрого прототипирования и отладки. **[Keras](https://keras.io/)** - очень популярный и полезный фреймворк DL, который позволяет быстро реализовывать нейронный сети и имеет множество полезных функций.


<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Image credit: https://habr.com/post/334380/</i><p>

Мы будем использовать **PyTorch**, поскольку он активно развивается и поддерживается AI-сообществом 

## Установка

Подробную инструкцию по установке PyTorch вы можете найти на [официальном сайте PyTorch](https://pytorch.org/).

## Синтаксис Фреймворка

In [1]:
import torch

Несколько фактов о PyTorch:
- динамический граф вычислений
- удобные модули `torch.nn` и `torchvision` для быстрого прототипирования нейронных сетей
- даже быстрее, чем TensorFlow на некоторых задачах
- позволяет легко использовать **GPU**

По своей сути PyTorch предоставляет две основные функции:

- n-мерный тензор, похожий на **numpy**, но может работать на графических процессорах
- Автоматическая дифференциация для построения и обучения нейронных сетей

Если бы PyTorch был формулой, она была бы такой:

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Давайте посмотрим, как мы можем использовать PyTorch для работы с векторами и тензорами.

Напомним, что **тензор** - это многомерный вектор, например :

`x = np.array ([1,2,3])` - вектор = тензор с 1 размерностью (точнее: `(3,)`)

`y = np.array ([[1, 2, 3], [4, 5, 6]])` - матрица = тензор с двумя измерениями (`(2, 3)` в данном случае)

`z = np.array ([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) `-" куб "(3, 3, 3) = тензор с тремя измерениями (` ( 3, 3, 3) `в этом случае)


Одним из реальных примеров трехмерного тензора является **изображение**, оно имеет 3 измерения: `высота`, `ширина` и `глубина канала` (глубина канала = 3 для цветных изображений, 1 для оттенков серого). Вы можете думать об этом как о параллелепипеде, состоящем из действительных чисел.


### Типы Тензоров

В PyTorch мы будем использовать `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) для всех вычислений.

Все типы:

In [2]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

### Создание тензора

In [3]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [4]:
a.shape

torch.Size([2])

In [5]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
b.shape

torch.Size([2, 3])

In [7]:
x = torch.FloatTensor(2,3,4)

In [8]:
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
x = torch.FloatTensor(100)
x

tensor([ 4.1598e-35,  0.0000e+00,  1.5579e-38,  0.0000e+00,  5.8154e-43,
         0.0000e+00,         nan,         nan,  4.4721e+21,  2.3079e+20,
         6.2689e+22,  4.7428e+30,  1.3563e-19,  1.3817e-19, -1.0752e+10,
        -9.9222e+10,  1.8910e+23,  7.1443e+31,  1.9603e-19,  1.8061e+28,
         7.5527e+28,  5.2839e-11,  2.7604e+20,  1.7744e+28,  2.0535e-19,
         1.3563e-19,  1.0426e-08, -2.3866e+10, -1.7558e+10,  1.8910e+23,
         7.1443e+31,  1.9603e-19,  1.8061e+28,  7.5527e+28,  5.2839e-11,
         1.1319e+21,  6.2688e+22,  4.7428e+30,  1.3563e-19,  1.6962e-07,
        -2.3866e+10, -1.7558e+10,  1.8910e+23,  7.1443e+31,  1.9603e-19,
         1.8061e+28,  4.3747e+31,  4.2964e+24,  7.1901e+28,  6.2706e+22,
         4.7428e+30,  1.3563e-19,  2.3303e-09, -6.0573e-09, -3.0816e-37,
         1.8037e+28,  6.8296e+22,  1.2690e+31,  7.0364e+22,  7.5527e+28,
         5.2839e-11,  4.1993e+12,  7.5338e+28,  1.3563e-19,  1.3563e-19,
         1.0426e-08, -2.3866e+10, -1.7558e+10,  1.2

In [10]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Примечание:** если вы создаете `torch.Tensor` с помощью следующего конструктора, он будет заполнен мусором из "случайных номеров":

In [11]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[         0,          0,         81,          0],
         [         0,          0,          0,          0]],

        [[         0,          0, 1633952379,  975331700],
         [1948416800,  796162149, 1767992432,  540680814]],

        [[1919906850, 1395550307,  677739113,  693973595],
         [ 539786530, 1952804130, 1952539745,  540680801]]], dtype=torch.int32)

### Инициализации тензоров

In [12]:
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x1, x3)

Инициализация случайного распределения

In [13]:
x = torch.randn((2,3))                # Normal(0, 1) с размером (2, 3)
x

tensor([[-0.5305,  0.9323, -0.6304],
        [ 0.4465,  0.9984,  0.1139]])

In [15]:
print(x.random_(0, 10))                      # Дискретное равномерно U[0, 10]
print(x.uniform_(0, 1))                      # Равномерно U[0, 1]
print(x.normal_(mean=0, std=1))              # Нормальное со средним 0 и дисперсией 1
print(x.bernoulli_(p=0.5))                   # bernoulli with parameter p

tensor([[3., 4., 0.],
        [5., 0., 1.]])
tensor([[0.5035, 0.7040, 0.3917],
        [0.9705, 0.5969, 0.6021]])
tensor([[-0.4106, -1.1387,  1.1408],
        [-0.7171, -0.0499, -1.0397]])
tensor([[0., 1., 0.],
        [0., 1., 1.]])


## Функции в Torch 

У всех функций Numpy есть своя пара в Torch.

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

### Изменение формы
`np.reshape()` == `torch.view()`:

In [16]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
b.view(3, 2).shape

torch.Size([3, 2])

**Примечание:** `torch.view ()` создает новый тензор, но старый остается неизменным

In [18]:
b.view(-1, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [19]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Изменение типа тензора

In [20]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [21]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [22]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

In [23]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [24]:
a.to(torch.uint8)

tensor([  1,   3, 249], dtype=torch.uint8)

In [25]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [26]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [27]:
a[0, 0]

tensor(100.)

In [28]:
a[0:2, 1]

tensor([ 20., 163.])

### Арифметические операции

| операция | аналоги |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

#### Сложение

In [29]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [30]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [31]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [32]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [33]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

#### Вычитание

In [34]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [35]:
a.sub(b) # copy

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [36]:
a.sub_(b) # inplace

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

#### Умножение (поэлементное)

In [37]:
a * b

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

In [38]:
a.mul(b)

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

#### Деление (поэлементное):

In [39]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [40]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

In [41]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Примечание:** все эти операции создают новые тензоры, старые тензоры остаются неизменными.

In [42]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [43]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

### Операторы сравнения

In [44]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [45]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [46]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [47]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [48]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

### Использование индексации по логической маске

In [49]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [50]:
b[a == b]

tensor([100., 200., 300.])

### Поэлементное применение **универсальных функций**

In [51]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [52]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [53]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [54]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [55]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [56]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [57]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [58]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

## Матричные операции

#### Транспонирование тензора

In [59]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [60]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

Это тоже не inplace-операция:

In [61]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

#### Скалярное произведение векторов

In [62]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [63]:
a.dot(b)

tensor(-141.)

In [64]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [65]:
a @ b

tensor(-141.)

In [66]:
type(a)

torch.Tensor

In [67]:
type(b)

torch.Tensor

In [68]:
type(a @ b)

torch.Tensor

#### Матричное произведение

In [69]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [70]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [71]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [72]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [73]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [74]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

Тензор `b` можно развернуть в одномерный массив с помощью функции `torch.view(-1)`, чтобы результат был вектором

In [75]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [76]:
b.view(-1)

tensor([ -1., -10., 100.])

In [77]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [78]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

In [79]:
y = torch.Tensor(2, 3, 4, 5)
z = torch.Tensor(2, 3, 5, 6)
(y @ z).shape

torch.Size([2, 3, 4, 6])

## Конвертация
#### Конвертация из Numpy в Pytorch:

In [80]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.11279604, 0.6079875 , 0.10992521],
       [0.08128184, 0.58763098, 0.64088495],
       [0.31386328, 0.71590387, 0.12312265]])

In [81]:
b = torch.from_numpy(a)
b

tensor([[0.1128, 0.6080, 0.1099],
        [0.0813, 0.5876, 0.6409],
        [0.3139, 0.7159, 0.1231]], dtype=torch.float64)

**Внимание!** `a` и `b` хранятся в одной и той же ячейке данных. Если именить один тензор, то изменится и другой.

In [82]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [83]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Конвертация из Torch в Numpy

In [84]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[4.7471e-35, 0.0000e+00, 4.7563e+30, 1.7753e+28],
         [1.8465e+25, 1.5144e+25, 6.1972e-04, 3.0821e+32],
         [6.9789e+22, 1.4610e-19, 1.7202e+22, 2.3316e-09]],

        [[2.1707e-18, 7.0062e+22, 2.1715e-18, 1.8991e+28],
         [1.7664e+22, 1.4580e-19, 1.8060e+28, 1.5766e-19],
         [1.4587e-19, 1.1576e+27, 3.2313e-18, 2.5171e-12]]])

In [85]:
type(a)

torch.Tensor

In [86]:
x = a.numpy()
x

array([[[4.74708700e-35, 0.00000000e+00, 4.75633004e+30, 1.77528927e+28],
        [1.84648818e+25, 1.51441670e+25, 6.19715895e-04, 3.08208075e+32],
        [6.97890859e+22, 1.46103697e-19, 1.72023038e+22, 2.33161090e-09]],

       [[2.17074423e-18, 7.00623823e+22, 2.17148187e-18, 1.89905234e+28],
        [1.76637291e+22, 1.45803469e-19, 1.80601830e+28, 1.57661930e-19],
        [1.45865753e-19, 1.15760565e+27, 3.23129607e-18, 2.51711022e-12]]],
      dtype=float32)

In [87]:
x.shape

(2, 3, 4)

In [88]:
type(x)

numpy.ndarray

## CUDA

<a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a> --- это программно-аппаратная архитектура параллельных вычислений, которая позволяет существенно увеличить вычислительную производительность благодаря использованию графических процессоров фирмы Nvidia. Для нас CUDA --- это драйвер, который позволяет нам проводить вычисления на GPU.

[CUDA documentation](https://docs.nvidia.com/cuda/)

Для вычислений на Pytorch мы можем использовать как CPU (Central Processing Unit), так и GPU (Graphical Processing Unit). Между ними можно легко переключаться, и это очень важно!

In [89]:
x = torch.FloatTensor(1024, 10024).uniform_()
x

tensor([[0.7988, 0.6687, 0.0634,  ..., 0.3695, 0.4353, 0.3944],
        [0.4358, 0.0743, 0.6010,  ..., 0.1132, 0.5281, 0.3772],
        [0.2212, 0.7566, 0.6308,  ..., 0.1202, 0.0655, 0.3389],
        ...,
        [0.6574, 0.4919, 0.0370,  ..., 0.9350, 0.0241, 0.3933],
        [0.8270, 0.7267, 0.2033,  ..., 0.1770, 0.2234, 0.6536],
        [0.8877, 0.0791, 0.4777,  ..., 0.9943, 0.4120, 0.0567]])

In [90]:
x.is_cuda

False

#### Кладём тензор на GPU

In [91]:
!nvidia-smi

Wed Oct 26 07:09:38 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [92]:
x = x.cuda()

In [93]:
!nvidia-smi

Wed Oct 26 07:09:44 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    26W /  70W |    648MiB / 15109MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [94]:
x

tensor([[0.7988, 0.6687, 0.0634,  ..., 0.3695, 0.4353, 0.3944],
        [0.4358, 0.0743, 0.6010,  ..., 0.1132, 0.5281, 0.3772],
        [0.2212, 0.7566, 0.6308,  ..., 0.1202, 0.0655, 0.3389],
        ...,
        [0.6574, 0.4919, 0.0370,  ..., 0.9350, 0.0241, 0.3933],
        [0.8270, 0.7267, 0.2033,  ..., 0.1770, 0.2234, 0.6536],
        [0.8877, 0.0791, 0.4777,  ..., 0.9943, 0.4120, 0.0567]],
       device='cuda:0')

In [95]:
x = x.cpu()
!nvidia-smi

torch.cuda.empty_cache()
!nvidia-smi

Wed Oct 26 07:09:52 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0    26W /  70W |    650MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [96]:
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")

x = x.to(device)
x

tensor([[0.7988, 0.6687, 0.0634,  ..., 0.3695, 0.4353, 0.3944],
        [0.4358, 0.0743, 0.6010,  ..., 0.1132, 0.5281, 0.3772],
        [0.2212, 0.7566, 0.6308,  ..., 0.1202, 0.0655, 0.3389],
        ...,
        [0.6574, 0.4919, 0.0370,  ..., 0.9350, 0.0241, 0.3933],
        [0.8270, 0.7267, 0.2033,  ..., 0.1770, 0.2234, 0.6536],
        [0.8877, 0.0791, 0.4777,  ..., 0.9943, 0.4120, 0.0567]],
       device='cuda:0')

Умножим два тензора в GPU и вернём результат обратно на CPU:

In [97]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [98]:
c

tensor([[0.0736, 0.1250, 0.2986,  ..., 0.8229, 0.1250, 0.1251],
        [0.0705, 0.0029, 0.0128,  ..., 0.3016, 0.0919, 0.6086],
        [0.5362, 0.1298, 0.3098,  ..., 0.1299, 0.1793, 0.3188],
        ...,
        [0.0878, 0.1516, 0.1516,  ..., 0.0312, 0.1855, 0.2693],
        [0.2314, 0.0636, 0.3349,  ..., 0.0528, 0.3029, 0.1394],
        [0.1495, 0.3485, 0.0053,  ..., 0.1860, 0.3974, 0.0253]])

In [99]:
a

tensor([[0.1624, 0.4435, 0.3435,  ..., 0.9909, 0.8953, 0.3492],
        [0.0901, 0.0029, 0.0234,  ..., 0.4444, 0.1494, 0.9028],
        [0.6626, 0.3195, 0.4650,  ..., 0.2363, 0.7848, 0.7799],
        ...,
        [0.2054, 0.2280, 0.4130,  ..., 0.0485, 0.9510, 0.2982],
        [0.5110, 0.2342, 0.8139,  ..., 0.1141, 0.3668, 0.2001],
        [0.5393, 0.4928, 0.5008,  ..., 0.5394, 0.4525, 0.9338]])

Тензоры из разных областей памяти не совместимы:

In [100]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [101]:
a + b

RuntimeError: ignored

### Пример работы на GPU

In [102]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [103]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# проверить наличие CUDA (NVIDIA GPU)
if torch.cuda.is_available():
    # получить имя устройства CUDA
    device = torch.device('cuda')          # Объект CUDA-устройства
    y = torch.ones_like(x, device=device)  # создаем тензор на GPU
    x = x.to(device)                       # или просто `.to("cuda")`
    z = x + y
    print(z)
    # вы можете установить тип во время операции `.to`
    print(z.to("cpu", torch.double))

tensor([[[1.5955, 1.0956, 1.5314, 1.7922, 1.3077],
         [1.3686, 1.4540, 1.4654, 1.0557, 1.5872],
         [1.6909, 1.6536, 1.2517, 1.5333, 1.4784],
         [1.0552, 1.1837, 1.7309, 1.3080, 1.1304],
         [1.5623, 1.9568, 1.5227, 1.0974, 1.3650]],

        [[1.8519, 1.8390, 1.2446, 1.8657, 1.8669],
         [1.2387, 1.1508, 1.3543, 1.2331, 1.1125],
         [1.8015, 1.7736, 1.3091, 1.3465, 1.4285],
         [1.3754, 1.6672, 1.7191, 1.2797, 1.5223],
         [1.0936, 1.8204, 1.7436, 1.4528, 1.6046]],

        [[1.1393, 1.9612, 1.6936, 1.8007, 1.9046],
         [1.2451, 1.7582, 1.2820, 1.2671, 1.6589],
         [1.6079, 1.9380, 1.4777, 1.4053, 1.8415],
         [1.4573, 1.2213, 1.6183, 1.0586, 1.0866],
         [1.5915, 1.2227, 1.6752, 1.3349, 1.8988]],

        [[1.0124, 1.6088, 1.9872, 1.9019, 1.6240],
         [1.8747, 1.3411, 1.9928, 1.0011, 1.8243],
         [1.9012, 1.0054, 1.7794, 1.4579, 1.0622],
         [1.0747, 1.4851, 1.8076, 1.2985, 1.2535],
         [1.6670, 1.2967,

In [104]:
x = torch.rand([2000,3000])

In [105]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [106]:
x_cuda = x.to(device)

In [107]:
%time y = (x - x + x * 10.0) ** 2

CPU times: user 27.9 ms, sys: 1.82 ms, total: 29.7 ms
Wall time: 29.6 ms


In [108]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 1.46 ms, sys: 871 µs, total: 2.33 ms
Wall time: 8.84 ms


## AutoGrad

За что мы любим PyTorch - за то, что в нём можно автоматически дифференцировать функции! Дифференцирование функций происходит по формуле производной композиции.

**Правило производной композиции (a.k.a. backpropagation)**

Пусть есть функция $f(w(\theta))$. Вычислим её производную:
$${\frac  {\partial{f}}{\partial{\theta}}}
={\frac  {\partial{f}}{\partial{w}}}\cdot {\frac  {\partial{w}}{\partial{\theta}}}$$


*Как рассказывалось на лекции, в многомерном случае можно записать аналог этой формулы:*
$$
D_\theta(f\circ w) = D_{w(\theta)}(f)\circ D_\theta(w)
$$

Простой пример обратного распространения градиента:

$$y = \sin \left(x_2^2(x_1 + x_2)\right)$$

<img src="https://ars.els-cdn.com/content/image/1-s2.0-S0010465515004099-gr1.jpg" width=700></img>
